// Generated by scripts/build-steakhouse-menu.mjs — do not edit by hand.
//
// The 19th Hole menu. Photography is Del Frisco's Double Eagle Steakhouse
// (Boston) via Uber Eats, used here as realistic placeholder plating; prices and
// copy are written for this prototype and are not the restaurant's own.

export type MenuCategory = "Starters" | "Salads" | "Steaks" | "Chops & Seafood" | "Sides" | "Sauces" | "Desserts";

export interface MenuItem {
    id: string;
    name: string;
    category: MenuCategory;
    price: number;
    description: string;
    /** Path under the store-images static dir. */
    path: string;
}

export const menuCategories: MenuCategory[] = ["Starters","Salads","Steaks","Chops & Seafood","Sides","Sauces","Desserts"];

export const menuItems: MenuItem[] = [
    { id: "crispy-calamari", name: "Crispy Calamari", category: "Starters", price: 18, description: "Flash-fried calamari, sweet peppers, lemon aioli.", path: "food/19th-hole/crispy-calamari.jpg" },
    { id: "ahi-tuna-tartare", name: "Ahi Tuna Tartare", category: "Starters", price: 24, description: "Hand-cut ahi, avocado, citrus soy, crisp wontons.", path: "food/19th-hole/ahi-tuna-tartare.jpg" },
    { id: "chili-glazed-shrimp", name: "Chili-Glazed Shrimp", category: "Starters", price: 21, description: "Crispy shrimp, sweet chili glaze, sesame slaw.", path: "food/19th-hole/chili-glazed-shrimp.jpg" },
    { id: "shrimp-cocktail", name: "Shrimp Cocktail", category: "Starters", price: 26, description: "Five chilled jumbo shrimp, horseradish cocktail sauce.", path: "food/19th-hole/shrimp-cocktail.jpg" },
    { id: "jumbo-lump-crab-cake", name: "Jumbo Lump Crab Cake", category: "Starters", price: 27, description: "All lump crab, almost no filler, roasted pepper cream.", path: "food/19th-hole/jumbo-lump-crab-cake.jpg" },
    { id: "crispy-rice-tuna-bites", name: "Crispy Rice Tuna Bites", category: "Starters", price: 22, description: "Seared tuna over crisped sushi rice, spicy aioli.", path: "food/19th-hole/crispy-rice-tuna-bites.jpg" },
    { id: "steakhouse-roll", name: "Steakhouse Roll", category: "Starters", price: 23, description: "Seared filet, avocado and chive, chipotle drizzle.", path: "food/19th-hole/steakhouse-roll.jpg" },
    { id: "honey-butter-rolls", name: "Honey Butter Rolls", category: "Starters", price: 9, description: "Pull-apart brioche rolls, warm honey butter.", path: "food/19th-hole/honey-butter-rolls.jpg" },
    { id: "herb-crusted-lamb-chops", name: "Herb-Crusted Lamb Chops", category: "Starters", price: 29, description: "Three chops, salsa verde, charred scallion.", path: "food/19th-hole/herb-crusted-lamb-chops.jpg" },
    { id: "caesar-salad", name: "Caesar Salad", category: "Salads", price: 15, description: "Whole romaine hearts, parmesan, garlic croutons.", path: "food/19th-hole/caesar-salad.jpg" },
    { id: "iceberg-wedge", name: "Iceberg Wedge", category: "Salads", price: 16, description: "Blue cheese, heirloom tomato, smoked bacon.", path: "food/19th-hole/iceberg-wedge.jpg" },
    { id: "burrata-and-tomato", name: "Burrata & Heirloom Tomato", category: "Salads", price: 19, description: "Creamy burrata, aged balsamic, basil oil.", path: "food/19th-hole/burrata-and-tomato.jpg" },
    { id: "chopped-bacon-salad", name: "Chopped Salad with Thick-Cut Bacon", category: "Salads", price: 18, description: "Slab bacon, watermelon radish, buttermilk dressing.", path: "food/19th-hole/chopped-bacon-salad.jpg" },
    { id: "filet-mignon-8oz", name: "Filet Mignon 8 oz", category: "Steaks", price: 62, description: "Center-cut prime tenderloin, seared and rested.", path: "food/19th-hole/filet-mignon-8oz.jpg" },
    { id: "petite-filet-6oz", name: "Petite Filet 6 oz", category: "Steaks", price: 52, description: "The smaller cut of the same prime tenderloin.", path: "food/19th-hole/petite-filet-6oz.jpg" },
    { id: "ny-strip-16oz", name: "New York Strip 16 oz", category: "Steaks", price: 68, description: "Prime strip loin, heavy crust, deeply marbled.", path: "food/19th-hole/ny-strip-16oz.jpg" },
    { id: "ribeye-16oz", name: "Ribeye 16 oz", category: "Steaks", price: 72, description: "Prime ribeye, the richest cut on the board.", path: "food/19th-hole/ribeye-16oz.jpg" },
    { id: "tomahawk-ribeye", name: "Tomahawk Ribeye 45 oz", category: "Steaks", price: 155, description: "Long-bone ribeye carved tableside. Serves two.", path: "food/19th-hole/tomahawk-ribeye.jpg" },
    { id: "porterhouse-for-two", name: "Porterhouse for Two 40 oz", category: "Steaks", price: 145, description: "Strip and filet on the bone, sliced for sharing.", path: "food/19th-hole/porterhouse-for-two.jpg" },
    { id: "prime-sliced-steak", name: "Prime Sliced Steak", category: "Steaks", price: 58, description: "Sliced strip, sea salt, aged balsamic.", path: "food/19th-hole/prime-sliced-steak.jpg" },
    { id: "bone-in-strip", name: "Bone-In Strip 20 oz", category: "Steaks", price: 78, description: "Strip left on the bone for a heavier char.", path: "food/19th-hole/bone-in-strip.jpg" },
    { id: "steakhouse-trio", name: "Steakhouse Trio", category: "Steaks", price: 89, description: "Three filet medallions — oscar, scallop and shrimp.", path: "food/19th-hole/steakhouse-trio.jpg" },
    { id: "filet-and-lobster", name: "Filet & Lobster Tail", category: "Steaks", price: 98, description: "Six-ounce filet with a cold-water tail and drawn butter.", path: "food/19th-hole/filet-and-lobster.jpg" },
    { id: "filet-oscar", name: "Filet Oscar", category: "Steaks", price: 74, description: "Filet topped with lump crab, asparagus and béarnaise.", path: "food/19th-hole/filet-oscar.jpg" },
    { id: "bone-in-ribeye-chop", name: "Bone-In Ribeye 22 oz", category: "Chops & Seafood", price: 84, description: "Frenched bone, prime ribeye, coarse pepper crust.", path: "food/19th-hole/bone-in-ribeye-chop.jpg" },
    { id: "veal-chop", name: "Veal Chop", category: "Chops & Seafood", price: 66, description: "Thick-cut milk-fed chop, herb butter.", path: "food/19th-hole/veal-chop.jpg" },
    { id: "center-cut-pork-chop", name: "Center-Cut Pork Chop", category: "Chops & Seafood", price: 42, description: "Brined double chop, cider pan sauce.", path: "food/19th-hole/center-cut-pork-chop.jpg" },
    { id: "blackened-salmon", name: "Blackened Salmon", category: "Chops & Seafood", price: 42, description: "Cajun-spiced fillet, chili-honey glaze.", path: "food/19th-hole/blackened-salmon.jpg" },
    { id: "chilean-sea-bass", name: "Chilean Sea Bass", category: "Chops & Seafood", price: 52, description: "Miso-glazed bass over creamed spinach.", path: "food/19th-hole/chilean-sea-bass.jpg" },
    { id: "seared-ahi-tuna", name: "Seared Ahi Tuna", category: "Chops & Seafood", price: 46, description: "Rare-seared ahi, wasabi crème, pickled carrot.", path: "food/19th-hole/seared-ahi-tuna.jpg" },
    { id: "lobster-tail", name: "Lobster Tail", category: "Chops & Seafood", price: 68, description: "Cold-water tail, drawn butter, charred lemon.", path: "food/19th-hole/lobster-tail.jpg" },
    { id: "lobster-shrimp-diavolo", name: "Lobster & Shrimp Diavolo", category: "Chops & Seafood", price: 54, description: "Lobster and shrimp in a spiced tomato cream.", path: "food/19th-hole/lobster-shrimp-diavolo.jpg" },
    { id: "grilled-jumbo-shrimp", name: "Grilled Jumbo Shrimp", category: "Chops & Seafood", price: 26, description: "Four shrimp, garlic butter, lemon.", path: "food/19th-hole/grilled-jumbo-shrimp.jpg" },
    { id: "crab-cake-napoleon", name: "Crab Cake Napoleon", category: "Chops & Seafood", price: 34, description: "Stacked crab cake, root vegetable slaw, demi.", path: "food/19th-hole/crab-cake-napoleon.jpg" },
    { id: "creamed-spinach", name: "Creamed Spinach", category: "Sides", price: 14, description: "The steakhouse standard, nutmeg and cream.", path: "food/19th-hole/creamed-spinach.jpg" },
    { id: "skillet-corn", name: "Skillet Corn", category: "Sides", price: 13, description: "Sweet corn, jalapeño, cream, blistered shishitos.", path: "food/19th-hole/skillet-corn.jpg" },
    { id: "lobster-mac-and-cheese", name: "Lobster Mac & Cheese", category: "Sides", price: 26, description: "Knuckle and claw meat, three cheeses, crumb top.", path: "food/19th-hole/lobster-mac-and-cheese.jpg" },
    { id: "potatoes-au-gratin", name: "Potatoes Au Gratin", category: "Sides", price: 14, description: "Layered and baked in cream until the top sets.", path: "food/19th-hole/potatoes-au-gratin.jpg" },
    { id: "whipped-potatoes", name: "Whipped Potatoes", category: "Sides", price: 12, description: "Butter-heavy, chive-finished.", path: "food/19th-hole/whipped-potatoes.jpg" },
    { id: "loaded-smashed-potatoes", name: "Loaded Smashed Potatoes", category: "Sides", price: 14, description: "Skin-on, bacon, sharp cheddar, scallion.", path: "food/19th-hole/loaded-smashed-potatoes.jpg" },
    { id: "loaded-baked-potato", name: "Loaded Baked Potato", category: "Sides", price: 13, description: "Sour cream, bacon, cheddar, chive.", path: "food/19th-hole/loaded-baked-potato.jpg" },
    { id: "grilled-asparagus", name: "Grilled Asparagus", category: "Sides", price: 15, description: "Charred spears, lemon and cracked pepper.", path: "food/19th-hole/grilled-asparagus.jpg" },
    { id: "broccolini", name: "Broccolini", category: "Sides", price: 13, description: "Garlic, chili flake, olive oil.", path: "food/19th-hole/broccolini.jpg" },
    { id: "steak-fries", name: "Steak Fries", category: "Sides", price: 11, description: "Thick-cut, twice-fried, sea salt.", path: "food/19th-hole/steak-fries.jpg" },
    { id: "wild-mushrooms", name: "Sautéed Wild Mushrooms", category: "Sides", price: 14, description: "Mixed mushrooms, thyme, sherry butter.", path: "food/19th-hole/wild-mushrooms.jpg" },
    { id: "asparagus-oscar", name: "Asparagus Oscar", category: "Sides", price: 24, description: "Asparagus, jumbo lump crab, béarnaise.", path: "food/19th-hole/asparagus-oscar.jpg" },
    { id: "bearnaise", name: "Béarnaise", category: "Sauces", price: 4, description: "Tarragon, shallot, clarified butter.", path: "food/19th-hole/bearnaise.jpg" },
    { id: "chimichurri", name: "Chimichurri", category: "Sauces", price: 4, description: "Parsley, oregano, garlic, red wine vinegar.", path: "food/19th-hole/chimichurri.jpg" },
    { id: "demi-glace", name: "Steakhouse Demi-Glace", category: "Sauces", price: 4, description: "Reduced veal stock, red wine.", path: "food/19th-hole/demi-glace.jpg" },
    { id: "horseradish-cream", name: "Horseradish Cream", category: "Sauces", price: 4, description: "Fresh-grated horseradish, crème fraîche.", path: "food/19th-hole/horseradish-cream.jpg" },
    { id: "peppercorn-cream", name: "Peppercorn Cream", category: "Sauces", price: 4, description: "Cracked green peppercorn, cognac.", path: "food/19th-hole/peppercorn-cream.jpg" },
    { id: "whiskey-peppercorn", name: "Whiskey Peppercorn", category: "Sauces", price: 4, description: "Bourbon-laced pan sauce.", path: "food/19th-hole/whiskey-peppercorn.jpg" },
    { id: "herb-butter", name: "Herb Butter", category: "Sauces", price: 4, description: "Compound butter, parsley and chive.", path: "food/19th-hole/herb-butter.jpg" },
    { id: "sauce-trio", name: "Sauce Trio", category: "Sauces", price: 10, description: "Béarnaise, chimichurri and peppercorn cream.", path: "food/19th-hole/sauce-trio.jpg" },
    { id: "lemon-cake", name: "Lemon Doberge Cake", category: "Desserts", price: 14, description: "Six thin layers, lemon curd, cream cheese icing.", path: "food/19th-hole/lemon-cake.jpg" },
    { id: "chocolate-layer-cake", name: "Chocolate Layer Cake", category: "Desserts", price: 14, description: "Dark chocolate ganache, whipped cream.", path: "food/19th-hole/chocolate-layer-cake.jpg" },
    { id: "butter-cake", name: "Butter Cake", category: "Desserts", price: 15, description: "Warm from the oven with vanilla ice cream.", path: "food/19th-hole/butter-cake.jpg" },
    { id: "strawberries-and-cream", name: "Strawberries & Cream", category: "Desserts", price: 13, description: "Macerated berries, chantilly, shortbread.", path: "food/19th-hole/strawberries-and-cream.jpg" },
];

export const menuByCategory = (category: MenuCategory) => menuItems.filter((i) => i.category === category);
